#服务端口号
server:
  port: 8002

spring:
  application:
    #服务名称
    name: cloud-order-service
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zero2one?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai

mybatis-plus:
  #扫描资源（resources）路径下，mapper目录的所有以 .xml 结尾的mapper文件
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true
